version: "3.8"
services:
  bskybot:
    build: .
    restart: unless-stopped
    networks:
      - bun

  jetstream:
    image: "ghcr.io/juni-b-queer/jetstream:main"
    container_name: jetstream
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data

networks:
  bun:
    driver: bridge
