version: "3.8"
services:
  bskybot:
    depends_on:
      - jetstream
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sessionData:/sessionData
    networks:
      - bun

#  bskybot:
#    image: "ghcr.io/juni-b-queer/test-firehose-bot:update-agent-to-class"
#    depends_on:
#      - jetstream
#    restart: unless-stopped
#    env_file:
#      - .env
#    networks:
#      - bun

  jetstream:
    image: "ghcr.io/juni-b-queer/jetstream-new:personal-branch"
    container_name: jetstream
    restart: unless-stopped
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data
    networks:
      - bun

networks:
  bun:
    driver: bridge
